on:
  push:
    branches:
      - main
  release:
    types: [published]
name: editor.js - raw tool - npm publish
jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      approved-release: ${{steps.check-release.outputs.approved-release}}
    if: github.event_name == 'release'
    steps:
      - id: check-release
        run: |
          if [[ ${{ github.event.release.tag_name }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo ::set-output name=approved-release::"true"; fi
  build-and-publish:
    needs: settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alemcombr'
      - name: NPM Install and Build
        run: |
          npm install
          npm run build
      - name: Publish
        if: needs.settings.outputs.approved-release == 'true'
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
